[package]
name = "r2v"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
image = "0.25.1"
rand = "0.8.5"
rayon = "1.10.0"
tiny-skia = "0.11.4"
chrono = "0.4"
nalgebra = "0.33.0"
